// interface MessageListProps {
//   id: number
//   position: string
//   message: string
//   createdAt?: string
//   updatedAt?: string
//   deletedAt?: string | null
// }

export interface ChatMessage {
  id: number
  senderId: number
  receiverId: number
  message: string
  timestamp: Date
  isRead: boolean
  isDeleted: boolean
}

export const chatMessages: ChatMessage[] = [
  {
    id: 1,
    senderId: 1,
    receiverId: 2,
    message: 'Hello, how are you?',
    timestamp: new Date('2022-05-01T14:30:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 2,
    senderId: 2,
    receiverId: 1,
    message: "I'm good, thanks for asking!",
    timestamp: new Date('2022-05-01T14:31:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 3,
    senderId: 1,
    receiverId: 2,
    message: 'What have you been up to lately?',
    timestamp: new Date('2022-05-01T14:32:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 4,
    senderId: 2,
    receiverId: 1,
    message: 'Not much, just working and spending time with family.',
    timestamp: new Date('2022-05-01T14:33:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 5,
    senderId: 1,
    receiverId: 2,
    message: "Sounds nice! How's your family doing?",
    timestamp: new Date('2022-05-01T14:34:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 6,
    senderId: 2,
    receiverId: 1,
    message: "They're doing well, thanks for asking!",
    timestamp: new Date('2022-05-01T14:35:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 7,
    senderId: 1,
    receiverId: 2,
    message: "That's great to hear!",
    timestamp: new Date('2022-05-01T14:36:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 8,
    senderId: 2,
    receiverId: 1,
    message: 'How about you? What have you been up to?',
    timestamp: new Date('2022-05-01T14:37:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 9,
    senderId: 1,
    receiverId: 2,
    message: 'Just trying to stay busy with work and hobbies.',
    timestamp: new Date('2022-05-01T14:38:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 10,
    senderId: 2,
    receiverId: 1,
    message: 'Nice! What are some of your hobbies?',
    timestamp: new Date('2022-05-01T14:39:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 11,
    senderId: 1,
    receiverId: 2,
    message: 'I like to play sports, read, and watch movies.',
    timestamp: new Date('2022-05-01T14:40:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 12,
    senderId: 2,
    receiverId: 1,
    message: "Cool! What's your favorite sport?",
    timestamp: new Date('2022-05-01T14:41:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 13,
    senderId: 1,
    receiverId: 2,
    message: 'I like to play basketball.',
    timestamp: new Date('2022-05-01T14:42:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 14,
    senderId: 2,
    receiverId: 1,
    message: "That's awesome! I like to play too.",
    timestamp: new Date('2022-05-01T14:43:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 15,
    senderId: 1,
    receiverId: 2,
    message: 'Nice! How often do you play?',
    timestamp: new Date('2022-05-01T14:44:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 16,
    senderId: 2,
    receiverId: 1,
    message: 'I try to play at least once a week.',
    timestamp: new Date('2022-05-01T14:45:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 17,
    senderId: 1,
    receiverId: 2,
    message: "That's awesome! I wish I could play more often.",
    timestamp: new Date('2022-05-01T14:46:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 18,
    senderId: 2,
    receiverId: 1,
    message: "Yeah, it's tough to find time sometimes.",
    timestamp: new Date('2022-05-01T14:47:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 19,
    senderId: 1,
    receiverId: 2,
    message: "Yeah, but it's worth it when you do get the chance to play.",
    timestamp: new Date('2022-05-01T14:48:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 20,
    senderId: 2,
    receiverId: 1,
    message: 'Definitely!',
    timestamp: new Date('2022-05-01T14:49:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 21,
    senderId: 1,
    receiverId: 2,
    message: 'Well, I have to go now. It was great chatting with you!',
    timestamp: new Date('2022-05-01T14:50:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 22,
    senderId: 2,
    receiverId: 1,
    message: 'Yeah, it was great chatting with you too!',
    timestamp: new Date('2022-05-01T14:51:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 23,
    senderId: 1,
    receiverId: 2,
    message: 'Bye!',
    timestamp: new Date('2022-05-01T14:52:00'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 24,
    senderId: 1,
    receiverId: 2,
    message: 'Bye!',
    timestamp: new Date('2022-05-01T14:52:01'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 25,
    senderId: 1,
    receiverId: 2,
    message: 'Bye!',
    timestamp: new Date('2022-05-01T14:52:02'),
    isRead: true,
    isDeleted: false,
  },
  {
    id: 26,
    senderId: 2,
    receiverId: 1,
    message: 'Bye!',
    timestamp: new Date('2022-05-01T14:53:00'),
    isRead: true,
    isDeleted: false,
  },
]
